### ISSUE TITLE
abcjs blocks break Slides core plugin ('presentation mode')

### ISSUE THREAD

**Issue by jakebeamish** [TilBlechschmidt/obsidian-plugin-abcjs#7]
Choosing 'Start presentation' on a file that does not have any abcjs blocks works as expected. However, when trying to do the same with a file that has abcjs blocks in it, nothing happens. I don't understand if this issue could be with this plugin, or with the core plugin Slides.

**Comment by TilBlechschmidt** [comment]
It indeed seems to be an issue with the plugin. It attempts to replace the raw code block with the abcjs target node. However, for some unknown reason, this does not work in presentation mode.

Stack trace for future reference:
```javascript
app.js:1 DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at MusicPlugin.postprocessor (eval at <anonymous> (app://obsidian.md/app.js:1:615835), <anonymous>:17647:12)
    at Function.t.postProcess (app://obsidian.md/app.js:1:660111)
    at t.<anonymous> (app://obsidian.md/app.js:1:906710)
    at app://obsidian.md/app.js:1:2999
    at Object.next (app://obsidian.md/app.js:1:3104)
    at s (app://obsidian.md/app.js:1:1843)
```

**Comment by jakebeamish** [comment]
Thanks for having a look! Sorry I'm pretty incapable when it comes to anything more complicated than a line or two of CSS!

**Comment by TilBlechschmidt** [comment]
Not to worry, every contribution is welcome even if it is just a bug report or a line of CSS 😉

**Comment by jakebeamish** [comment]
Understandable, no worries!
